export const SET_ENTITY = "SET_ENTITY";
export const ADD_ENTITY = "ADD_ENTITY";
export const UPDATE_ENTITY = "UPDATE_ENTITY";
export const DELETE_ENTITY = "DELETE_ENTITY";
export const RESET_STATE = "RESET_STATE";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";

export const ADDED_INGREDIENT = "ADDED_INGREDIENT";
export const ADD_TO_CART = "ADD_TO_CART";
export const SET_DOUGH = "SET_DOUGH";
export const SET_SAUCE = "SET_SAUCE";
export const SET_PIZZA_NAME = "SET_PIZZA_NAME";
export const UPDATE_PIZZA_PARAMS = "UPDATE_PIZZA_PARAMS";
export const UPDATE_INGREDIENT = "UPDATE_INGREDIENT";
